sudo: false
language: node_js
node_js:
  - "6.0"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install

script:
  - yarn lint
  - yarn test

after_success:
  - yarn codecov
